### ISSUE TITLE
What tools are used to draw the pictures in the book?

### ISSUE THREAD

**Issue by jinrunsen** [programming-kubernetes/suggestions#7]
Excuse me, I know this question has nothing to do with this project, but I can't find any clues.

**Comment by mhausenblas** [comment]
@gasxia I'm not 100% certain since the figures are drawn by O'Reilly, they have dedicated folks there who do that, based on our own scribbles. If you want me to, I can reach out to our editor and ask …

**Comment by jinrunsen** [comment]
Thank you, I think I found the answer. I found this document. [O’Reilly Media Illustration Guidelines](http://oreillymedia.github.io/production-resources/illustrations/)
